import PhysicsModel.Geometry4
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.Ring

/-! # Coarse four-geometry from a finite relational quantum chart

Emergent chart components are relational observables attached to finite quantum
nodes.  Their weighted two-point Gram matrix defines a symmetric coarse metric.
Metric derivatives and an inverse metric then produce the usual Levi--Civita
connection, now as a finite algebraic construction feeding `Geometry4`.
-/

namespace PhysicsModel.CoarseGeometry4

open scoped BigOperators
open PhysicsModel.Geometry4

universe u

structure RelationalChart (Node : Type u) [Fintype Node] where
  coordinate : Node → Index → ℝ
  weight : Node → ℝ
  weight_nonnegative : ∀ node, 0 ≤ weight node

namespace RelationalChart

variable {Node : Type u} [Fintype Node]

/-- Weighted two-point/Gram coarse metric. -/
noncomputable def metric (chart : RelationalChart Node) : Metric :=
  fun μ ν => ∑ node, chart.weight node *
    chart.coordinate node μ * chart.coordinate node ν

theorem metric_symmetric (chart : RelationalChart Node) :
    ∀ μ ν, chart.metric μ ν = chart.metric ν μ := by
  intro μ ν
  unfold metric
  apply Finset.sum_congr rfl
  intro node _
  ring

/-- Every diagonal metric component is nonnegative because it is a weighted square. -/
theorem metric_diagonal_nonnegative (chart : RelationalChart Node) (μ : Index) :
    0 ≤ chart.metric μ μ := by
  unfold metric
  apply Finset.sum_nonneg
  intro node _
  have hw := chart.weight_nonnegative node
  rw [mul_assoc]
  exact mul_nonneg hw (mul_self_nonneg _)

/-- Zero-weight nodes do not affect the emergent metric. -/
theorem zero_weight_term (chart : RelationalChart Node) (node : Node)
    (zeroWeight : chart.weight node = 0) (μ ν : Index) :
    chart.weight node * chart.coordinate node μ * chart.coordinate node ν = 0 := by
  rw [zeroWeight]
  simp

/-- Binary refinement: duplicate every relational node and split its weight equally. -/
noncomputable def binaryRefinement (chart : RelationalChart Node) :
    RelationalChart (Node × Fin 2) where
  coordinate := fun refined μ => chart.coordinate refined.1 μ
  weight := fun refined => chart.weight refined.1 / 2
  weight_nonnegative := by
    intro refined
    exact div_nonneg (chart.weight_nonnegative refined.1) (by norm_num)

/-- The emergent Gram metric is exactly independent of this refinement resolution. -/
theorem binaryRefinement_metric_preserved (chart : RelationalChart Node) :
    chart.binaryRefinement.metric = chart.metric := by
  funext μ ν
  unfold metric binaryRefinement
  rw [Fintype.sum_prod_type]
  apply Finset.sum_congr rfl
  intro node _
  change (∑ _ : Fin 2, (chart.weight node / 2) *
      chart.coordinate node μ * chart.coordinate node ν) = _
  rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin]
  norm_num
  ring

end RelationalChart

/-- First derivatives `∂_κ g_{μν}` of the coarse metric. -/
abbrev MetricDerivative := Index → Metric

def SymmetricMetricDerivative (derivative : MetricDerivative) : Prop :=
  ∀ direction μ ν, derivative direction μ ν = derivative direction ν μ

/-- Levi--Civita connection
`Γ^ρ_{μν}=1/2 g^{ρσ}(∂_μg_{σν}+∂_νg_{σμ}-∂_σg_{μν})`. -/
noncomputable def leviCivita (inverseMetric : Metric)
    (derivative : MetricDerivative) : Connection :=
  fun ρ μ ν => (1 / 2 : ℝ) * ∑ σ,
    inverseMetric ρ σ *
      (derivative μ σ ν + derivative ν σ μ - derivative σ μ ν)

/-- Symmetry of metric derivatives makes the constructed connection torsion free. -/
theorem leviCivita_torsionFree (inverseMetric : Metric)
    (derivative : MetricDerivative)
    (symmetric : SymmetricMetricDerivative derivative) :
    TorsionFree (leviCivita inverseMetric derivative) := by
  intro ρ μ ν
  unfold leviCivita
  congr 1
  apply Finset.sum_congr rfl
  intro σ _
  rw [symmetric σ μ ν]
  ring

@[simp] theorem leviCivita_zero_derivative (inverseMetric : Metric) :
    leviCivita inverseMetric 0 = 0 := by
  funext ρ μ ν
  simp [leviCivita]

/-- Curvature generated by the coarse Levi--Civita connection and its derivative. -/
noncomputable def curvature (inverseMetric : Metric) (metricDerivative : MetricDerivative)
    (connectionDerivative : ConnectionDerivative) : RiemannTensor :=
  riemann (leviCivita inverseMetric metricDerivative) connectionDerivative

/-- Fully assembled effective Einstein sector from relationally coarse data. -/
noncomputable def einsteinSector
    {Node : Type u} [Fintype Node] (chart : RelationalChart Node)
    (inverseMetric : Metric) (metricDerivative : MetricDerivative)
    (connectionDerivative : ConnectionDerivative) (stressEnergy : Metric)
    (cosmologicalConstant coupling : ℝ) : EinsteinSector EinsteinTensor4.Tensor :=
  Geometry4.sector chart.metric inverseMetric
    (leviCivita inverseMetric metricDerivative) connectionDerivative
    stressEnergy cosmologicalConstant coupling

/-- Constant coarse metric data with no connection derivative is flat. -/
theorem constant_chart_curvature_zero (inverseMetric : Metric) :
    curvature inverseMetric 0 0 = 0 := by
  unfold curvature
  rw [leviCivita_zero_derivative, riemann_zero]

/-- Constant relational charts with no matter satisfy the checked flat-vacuum equations. -/
theorem constant_chart_vacuum_residual
    {Node : Type u} [Fintype Node] (chart : RelationalChart Node)
    (inverseMetric : Metric) (coupling : ℝ) :
    (einsteinSector chart inverseMetric 0 0 0 0 coupling).residual = 0 := by
  unfold einsteinSector
  rw [leviCivita_zero_derivative]
  exact Geometry4.flat_vacuum_residual chart.metric inverseMetric coupling

end PhysicsModel.CoarseGeometry4
